[project]
name = "tableau-storytelling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.19.8",
    "numpy>=2.4.2",
    "polars>=1.38.0",
    "pyarrow>=23.0.0",
    "requests>=2.32.5",
    "ruff>=0.15.0",
]
